<div align="center" style="padding: 20px; border-radius: 10px; background-color: #f8f9fa; margin-bottom: 20px; border: 1px solid #e9ecef;">
<!-- Photo de Profil / Logo GitHub -->
<a href="https://github.com/KING-EMBBI" target="_blank" style="text-decoration: none;">
<img src="https://avatars.githubusercontent.com/u/181809601?s=400&u=0ae861f86d8d365864862c4d68aef5d1e9ebf1f4&v=4" alt="Osee Emmanuel Boum Bissemb" style="width: 140px; height: 140px; border-radius: 50%; border: 3px solid #2e7d32; object-fit: cover; box-shadow: 0 4px 8px rgba(0,0,0,0.1);"/>
</a>
<br><br>
<!-- Informations Personnelles -->
<span style="color: #1a252f; font-family: 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 28px; font-weight: 800; letter-spacing: 1px; text-transform: uppercase;">Osee Emmanuel Boum Bissemb</span>
<br>
<span style="color: #2e7d32; font-family: 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 16px; font-weight: 600; tracking-spacing: 0.5px;">🚀 Data Scientist & Analyste Statistique</span>
<hr style="width: 60%; border: 0; height: 1px; background-image: linear-gradient(to right, rgba(0, 0, 0, 0), rgba(46, 125, 50, 0.75), rgba(0, 0, 0, 0)); margin: 15px 0;"/>
<!-- Titre du Projet Évolutif -->
<span style="color: #111111; font-family: 'Impact', 'Arial Black', sans-serif; font-size: 22px; letter-spacing: 1.5px; text-transform: uppercase;">Telecom Churn Predictive Intelligence</span>
<br>
<span style="color: #555555; font-family: 'Segoe UI', Helvetica, Arial, sans-serif; font-size: 13px; font-weight: 400; font-style: italic;">Phase 2 — Data Cleaning & Intégrité des données</span>
</div>

<div style='background-color: #2e7d32; padding: 6px;'></div>

In [ ]:

import pandas as pd
import numpy as np
import os

# 1. Chargement du dataset original
raw_data_path = "c:/Users/osee0/OneDrive/Bureau/TELECOM CHURN/data/WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = pd.read_csv(raw_data_path)
print(f"🔹 Dimension initiale du dataset : {df.shape[0]} lignes, {df.shape[1]} colonnes/n")

🔹 Dimension initiale du dataset : 7043 lignes, 21 colonnes/n

In [29]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [30]:
# 2. Correction du piège de la colonne 'TotalCharges'
# On remplace les espaces vides cachés par des vrais NaN, puis on force le type en numérique
df['TotalCharges'] = df['TotalCharges'].replace(r'^/s*$', np.nan, regex=True)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [31]:
# 3. Traitement logique des valeurs manquantes (Imputation Métier)
# Inspectons les lignes où 'TotalCharges' est désormais NaN
missing_total_charges = df[df['TotalCharges'].isnull()]
print(f"⚠️ Nombre de vraies valeurs manquantes trouvées dans 'TotalCharges' : {len(missing_total_charges)}")

⚠️ Nombre de vraies valeurs manquantes trouvées dans 'TotalCharges' : 11

In [32]:
# Logique métier : Si le client a une fidélité (tenure) de 0 mois, c'est qu'il vient de souscrire.
# Ses charges totales sont donc légitimement de 0.
print("💡 Analyse métier : Vérification de la fidélité (tenure) pour ces profils...")
print(missing_total_charges['tenure'].value_counts())

💡 Analyse métier : Vérification de la fidélité (tenure) pour ces profils...
tenure
0    11
Name: count, dtype: int64

In [33]:

# Imputation : On remplace ces NaN par 0
df['TotalCharges'] = df['TotalCharges'].fillna(0.0)
print("✅ Imputation réussie : Valeurs manquantes fixées à 0.0 pour les nouveaux clients./n")

✅ Imputation réussie : Valeurs manquantes fixées à 0.0 pour les nouveaux clients./n

In [34]:
# 4. Nettoyage de la cohérence des chaînes de caractères
# Certaines colonnes ont des modalités redondantes (ex: 'No internet service' au lieu de 'No')
# Pour l'instant on garde la structure brute, mais on vérifie les doublons d'identifiants
duplicate_counts = df['customerID'].duplicated().sum()
print(f"🔹 Nombre de doublons d'identifiants (customerID) : {duplicate_counts}")

🔹 Nombre de doublons d'identifiants (customerID) : 0

In [40]:

# 5. Sauvegarde du Dataset Propre (Processed)
# Création du dossier s'il n'existe pas
output_dir = "c:/Users/osee0/OneDrive/Bureau/TELECOM CHURN/data"
os.makedirs(output_dir, exist_ok=True)

output_path = os.path.join(output_dir, "processed_telco.csv")
df.to_csv(output_path, index=False)
print(f"/n🚀 Dataset nettoyé exporté avec succès vers : {output_path}")

/n🚀 Dataset nettoyé exporté avec succès vers : c:/Users/osee0/OneDrive/Bureau/TELECOM CHURN/data\processed_telco.csv

In [36]:
# 6. Vérification finale du typage
print("/n📊 Structure finale du dataset nettoyé :")
df.info()

/n📊 Structure finale du dataset nettoyé :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [39]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7043.000000
mean        0.162147    32.371149       64.761692   2279.734304
std         0.368612    24.559481       30.090047   2266.794470
min         0.000000     0.000000       18.250000      0.000000
25%         0.000000     9.000000       35.500000    398.550000
50%         0.000000    29.000000       70.350000   1394.550000
75%         0.000000    55.000000       89.850000   3786.600000
max         1.000000    72.000000      118.750000   8684.800000